/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ServicesInteractiveScaleModelsRouteImport } from './routes/services.interactive-scale-models'
import { Route as ServicesInventorySelectorRouteImport } from './routes/services.inventory-selector'
import { Route as ServicesNeighborhoodMapRouteImport } from './routes/services.neighborhood-map'
import { Route as ServicesStillRenderRouteImport } from './routes/services.still-render'
import { Route as ServicesVideoWalkthroughRouteImport } from './routes/services.video-walkthrough'
import { Route as ServicesVrToursRouteImport } from './routes/services.vr-tours'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInteractiveScaleModelsRoute =
  ServicesInteractiveScaleModelsRouteImport.update({
    id: '/services/interactive-scale-models',
    path: '/services/interactive-scale-models',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInventorySelectorRoute =
  ServicesInventorySelectorRouteImport.update({
    id: '/services/inventory-selector',
    path: '/services/inventory-selector',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesNeighborhoodMapRoute = ServicesNeighborhoodMapRouteImport.update({
  id: '/services/neighborhood-map',
  path: '/services/neighborhood-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStillRenderRoute = ServicesStillRenderRouteImport.update({
  id: '/services/still-render',
  path: '/services/still-render',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVideoWalkthroughRoute =
  ServicesVideoWalkthroughRouteImport.update({
    id: '/services/video-walkthrough',
    path: '/services/video-walkthrough',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesVrToursRoute = ServicesVrToursRouteImport.update({
  id: '/services/vr-tours',
  path: '/services/vr-tours',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/terms': typeof TermsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/interactive-scale-models': typeof ServicesInteractiveScaleModelsRoute
  '/services/inventory-selector': typeof ServicesInventorySelectorRoute
  '/services/neighborhood-map': typeof ServicesNeighborhoodMapRoute
  '/services/still-render': typeof ServicesStillRenderRoute
  '/services/video-walkthrough': typeof ServicesVideoWalkthroughRoute
  '/services/vr-tours': typeof ServicesVrToursRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/terms': typeof TermsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/interactive-scale-models': typeof ServicesInteractiveScaleModelsRoute
  '/services/inventory-selector': typeof ServicesInventorySelectorRoute
  '/services/neighborhood-map': typeof ServicesNeighborhoodMapRoute
  '/services/still-render': typeof ServicesStillRenderRoute
  '/services/video-walkthrough': typeof ServicesVideoWalkthroughRoute
  '/services/vr-tours': typeof ServicesVrToursRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/terms': typeof TermsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/interactive-scale-models': typeof ServicesInteractiveScaleModelsRoute
  '/services/inventory-selector': typeof ServicesInventorySelectorRoute
  '/services/neighborhood-map': typeof ServicesNeighborhoodMapRoute
  '/services/still-render': typeof ServicesStillRenderRoute
  '/services/video-walkthrough': typeof ServicesVideoWalkthroughRoute
  '/services/vr-tours': typeof ServicesVrToursRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/terms'
    | '/projects/$slug'
    | '/services/interactive-scale-models'
    | '/services/inventory-selector'
    | '/services/neighborhood-map'
    | '/services/still-render'
    | '/services/video-walkthrough'
    | '/services/vr-tours'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/terms'
    | '/projects/$slug'
    | '/services/interactive-scale-models'
    | '/services/inventory-selector'
    | '/services/neighborhood-map'
    | '/services/still-render'
    | '/services/video-walkthrough'
    | '/services/vr-tours'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/terms'
    | '/projects/$slug'
    | '/services/interactive-scale-models'
    | '/services/inventory-selector'
    | '/services/neighborhood-map'
    | '/services/still-render'
    | '/services/video-walkthrough'
    | '/services/vr-tours'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  TermsRoute: typeof TermsRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ServicesInteractiveScaleModelsRoute: typeof ServicesInteractiveScaleModelsRoute
  ServicesInventorySelectorRoute: typeof ServicesInventorySelectorRoute
  ServicesNeighborhoodMapRoute: typeof ServicesNeighborhoodMapRoute
  ServicesStillRenderRoute: typeof ServicesStillRenderRoute
  ServicesVideoWalkthroughRoute: typeof ServicesVideoWalkthroughRoute
  ServicesVrToursRoute: typeof ServicesVrToursRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/interactive-scale-models': {
      id: '/services/interactive-scale-models'
      path: '/services/interactive-scale-models'
      fullPath: '/services/interactive-scale-models'
      preLoaderRoute: typeof ServicesInteractiveScaleModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/inventory-selector': {
      id: '/services/inventory-selector'
      path: '/services/inventory-selector'
      fullPath: '/services/inventory-selector'
      preLoaderRoute: typeof ServicesInventorySelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/neighborhood-map': {
      id: '/services/neighborhood-map'
      path: '/services/neighborhood-map'
      fullPath: '/services/neighborhood-map'
      preLoaderRoute: typeof ServicesNeighborhoodMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/still-render': {
      id: '/services/still-render'
      path: '/services/still-render'
      fullPath: '/services/still-render'
      preLoaderRoute: typeof ServicesStillRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/video-walkthrough': {
      id: '/services/video-walkthrough'
      path: '/services/video-walkthrough'
      fullPath: '/services/video-walkthrough'
      preLoaderRoute: typeof ServicesVideoWalkthroughRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/vr-tours': {
      id: '/services/vr-tours'
      path: '/services/vr-tours'
      fullPath: '/services/vr-tours'
      preLoaderRoute: typeof ServicesVrToursRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  TermsRoute: TermsRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ServicesInteractiveScaleModelsRoute: ServicesInteractiveScaleModelsRoute,
  ServicesInventorySelectorRoute: ServicesInventorySelectorRoute,
  ServicesNeighborhoodMapRoute: ServicesNeighborhoodMapRoute,
  ServicesStillRenderRoute: ServicesStillRenderRoute,
  ServicesVideoWalkthroughRoute: ServicesVideoWalkthroughRoute,
  ServicesVrToursRoute: ServicesVrToursRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
